/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import Ruidos.RuidoGamma;
import Ruidos.RuidoDeGauss;
import Ruidos.RuidoDeRayleigh;
import Ruidos.RuidoUniforme;
import Ruidos.RuidoCoherente;
import Ruidos.RuidoExponencialNegativo;
import Ruidos.RuidoDeSalyPimienta;
import Model.ImageData;
import Model.ImageDataByChannels;
import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author tony
 */
public class RuidoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form RuidoInterfaz
     */
    private Show showContent;
    ImagePanel ip1, ipAns;
    HistogramPanel hp1, hpAns;
    ImageData image1, imageAns;
    String name;
    String type;
    public RuidoInterfaz(app mainFrame) {
        initComponents();
        ip1 = null;
        hp1 = null;
        this.setVisible(true);
        showContent = new Show(mainFrame, this);
        if(mainFrame.currentWindow != null){
            this.image1 = mainFrame.currentWindow.getId();
            ip1 = showContent.drawImage(image1, ip1, imagePanel1);
            hp1 = showContent.drawHisto(image1, hp1, histo1, Color.blue);
        }
        name = mainFrame.currentWindow.fileName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        imagePanel1 = new javax.swing.JPanel();
        histo1 = new javax.swing.JPanel();
        imagePanel2 = new javax.swing.JPanel();
        histo2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sAmp = new javax.swing.JSpinner();
        sFx = new javax.swing.JSpinner();
        sFy = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sAlpha = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sVar = new javax.swing.JSpinner();
        sMed = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        sProba = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("abrir imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout histo1Layout = new javax.swing.GroupLayout(histo1);
        histo1.setLayout(histo1Layout);
        histo1Layout.setHorizontalGroup(
            histo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        histo1Layout.setVerticalGroup(
            histo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout histo2Layout = new javax.swing.GroupLayout(histo2);
        histo2.setLayout(histo2Layout);
        histo2Layout.setHorizontalGroup(
            histo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        histo2Layout.setVerticalGroup(
            histo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de ruido", "Coherente", "Gauss", "Rayleigh", "Sal y pimienta", "Exponencial negativo", "Gamma", "Uniforme" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Aplicar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sAmp.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.5d));

        sFx.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        sFy.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel1.setText("amplitud");

        jLabel2.setText("frec X");

        jLabel3.setText("frec Y");

        jLabel4.setText("alpha");

        sAlpha.setModel(new javax.swing.SpinnerNumberModel());

        jLabel5.setText("varianza");

        jLabel6.setText("media");

        sVar.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        sMed.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel7.setText("proba");

        sProba.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(histo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(histo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(sAmp, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(sFx)
                                    .addComponent(sFy))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(sAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(sVar)
                                    .addComponent(sMed))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(40, 40, 40))
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(sProba))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sAmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sProba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(sFy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(histo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(histo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Abrir imagen
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Aplicar
        int idx = jComboBox1.getSelectedIndex();
        int ans[][] = new int[image1.getWidth()][image1.getHeight()];
        int alto = image1.getHeight();
        int ancho = image1.getWidth();
        int imagen[][] = image1.getArray();
        
        double amp = (double)sAmp.getValue();
        double fx = (double)sFx.getValue();
        double fy = (double)sFy.getValue();
        int alfa = (int)sAlpha.getValue();
        double var = (double)sVar.getValue();
        double med = (double)sMed.getValue();
        double proba = (double)sProba.getValue();
        if(idx == 0){
            showMessageDialog(rootPane, "selecciona una opcion");
        }else if(idx == 1){//coherente
           RuidoCoherente rui = new RuidoCoherente(alto, ancho );
           ans = rui.adicionarRuidoCoherenteAImagen(imagen, amp, fx, fy);//amp, fx, fy
        }else if(idx == 2){//gauss
            RuidoDeGauss rui = new RuidoDeGauss(alto, ancho);
            ans = rui.adicionarRuidoDeGaussAImagen(imagen, var, med);//var med
        }else if(idx == 3){//rayleigh
            RuidoDeRayleigh rui = new RuidoDeRayleigh(alto, ancho);
            ans = rui.adicionarRuidoDeRayleigh(imagen, var);//var
        }else if(idx == 4){//sal y pimienta
            RuidoDeSalyPimienta rui = new RuidoDeSalyPimienta(alto, ancho);
            ans = rui.adicionarRuidoDeSalyPimienta(imagen, proba);//proba
        }else if(idx == 5){//exponencial negativo
            RuidoExponencialNegativo rui = new RuidoExponencialNegativo(alto, ancho);
            ans = rui.adicionarRuidoExponencialNegativoAImagen(imagen, var, med);// var y med
        }else if(idx == 6){//Gamma
            RuidoGamma rui = new RuidoGamma(alto, ancho);
            ans = rui.adicionarRuidoGammaAImagen(imagen, alfa, var);//alfa y var
        }else if(idx == 7){//uniforme
            RuidoUniforme rui = new RuidoUniforme(alto, ancho);
            ans = rui.adicionarRuidoUniformeAImagen(imagen, var, med);//car y med
        }
        double ansArray[][] = new double[ans.length][ans[0].length];
        for(int i = 0; i < image1.getHeight(); i++){
            for(int j = 0; j < image1.getWidth(); j++){
                ansArray[i][j] = ans[i][j];
            }
        }
        imageAns = new ImageDataByChannels(image1, image1.currentChannel, ansArray);
        ipAns = showContent.drawImage(imageAns, ipAns, imagePanel2);
        hpAns = showContent.drawHisto(imageAns, hpAns, histo2, Color.pink);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // guardar imagen
        Window formatWindow = new Window(imageAns, name + "ruido" + type);
        formatWindow.setImage2show(imageAns.getImageGray());
        showContent.setUpWindow(formatWindow);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // combo box action
        int idx = jComboBox1.getSelectedIndex();
        sAmp.setEnabled(false);
        sFx.setEnabled(false);
        sFy.setEnabled(false);
        sAlpha.setEnabled(false);
        sVar.setEnabled(false);
        sMed.setEnabled(false);
        sProba.setEnabled(false);
       
        if(idx == 1){
            sAmp.setEnabled(true);
            sFx.setEnabled(true);
            sFy.setEnabled(true);
            type = "_Coherente";
        }else if(idx == 2){
            sVar.setEnabled(true);
            sMed.setEnabled(true);
            type = "_Gauss";
        }else if(idx == 3){
            sVar.setEnabled(true);
            type = "_Rayleight";
        }else if(idx == 4){
            sProba.setEnabled(true);
            type = "_SalyPimienta";
        }else if(idx == 5){
            sVar.setEnabled(true);
            sMed.setEnabled(true);
            type = "_ExponencialNegativo";
        }else if(idx == 6){
            sAlpha.setEnabled(true);
            sVar.setEnabled(true);
            type = "_Gamma";
        }else if(idx == 7){
            sVar.setEnabled(true);
            sMed.setEnabled(true);
            type = "_Uniforme";
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel histo1;
    private javax.swing.JPanel histo2;
    private javax.swing.JPanel imagePanel1;
    private javax.swing.JPanel imagePanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner sAlpha;
    private javax.swing.JSpinner sAmp;
    private javax.swing.JSpinner sFx;
    private javax.swing.JSpinner sFy;
    private javax.swing.JSpinner sMed;
    private javax.swing.JSpinner sProba;
    private javax.swing.JSpinner sVar;
    // End of variables declaration//GEN-END:variables
}
